### PR TITLE
Cleanup & CameraBehavior Scaffolding

### PR DESCRIPTION
**Pull request by lillian-lemmer**
We need to talk about how to approach a few things outlined in the changes. To be clear, I do *not* want this merged into `master` until we iterate after dialogue.

### CODE REVIEW

**Comment by txanatan** [comment]
There is an issue with the camera, where things that are rendered to it after a certain point aren't present, and are instead transparent. This is shown in [these images](http://imgur.com/a/H5068). I'm investigating why right now.

**Comment by txanatan** [comment]
This doesn't happen with a smaller map:

test

(TMX used for testing: https://a.pomf.cat/lzaoib.tmx)

**Comment by txanatan** [comment]
And fixed. SurfaceLayers was calling `get_size()` on the Camera, which means that it was calling the parent function and returning the scale-up resolution as the size of the Surface, instead of the size of the source surface. Adding a `get_size()` function that returned the right size fixed this.

**Comment by lillian-lemmer** [comment]
Hm, @txanatan, that sounds like we're walking into murky waters. Let's have a long convo about this today.

**Comment by lillian-lemmer** [comment]
We may have to clarify some variables more descriptive, e.g., `source_surface` doesn't tell me much.

**Comment by lillian-lemmer** [comment]
Yeah you should be sending source surface, not camera!

**Comment by lillian-lemmer** [comment]
I've resolved this issue. :)

**Comment by txanatan** [comment]
An issue with your change is `camera.update()` is no longer being called as blitting doesn't go through the camera, instead directly to it's source surface. This means that when `scroll_to()` isn't being called (when the character isn't moving) updates won't be applied, breaking the character animation. Adding a call to `camera.update()` after the `layers.render()` call will fix this.

**Pull request merged**
